### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by A-Louarn** [ESIR2-IN-promo2017/Shader_Displacement_Mapping#1]
- [x] calculer la carte des distances
- [ ] retranscrire la carte des distances en javascript
- [ ] vertex shader
- [ ] fragment shader
- [ ] compléter la TODO list

**Comment by A-Louarn** [comment]
(normalement) la carte des distances doit être bonne (mais elle est calculée en C++, et pas en javascript)
